import './colors-type.scss'
import '../../components/body/body'
import '../../components/elements/square/square'
import '../../components/elements/logo-wrapper/logo-wrapper'
import './colors-title/colors-title'
