import './colors-type.scss'
import '../../components/body/body'
import '../../components/elements/block/block'
import '../../components/elements/logo-wrapper/logo-wrapper'
import './colors-title/colors-title'
