import './registration-accaunt.scss'
import '../../elements/input-text/input-text'
import '../../elements/toggle/one-toggle/one-toggle'
import '../../elements/buttons/long-btn/long-btn'
import '../../elements/buttons/short-btn/short-btn'
import '../../elements/radio-buttons/radio/radio'