import './registration.scss'
import '../../components/body/body'
import '../../components/header/header'
import '../../components/footer/footer'
import '../../components/common/copyright/copyright'
import '../../components/common/registration-account/registration-account'