import './registration-account.scss'
import '../../elements/input/input'
import '../../elements/one-toggle/one-toggle'
import '../../elements/buttons/long-btn/long-btn'
import '../../elements/buttons/short-btn/short-btn'
import '../../elements/radio/radio'