import './landing.scss'
import '../../components/body/body'
import '../../components/header/header'
import '../../components/footer/footer'
import '../../components/common/copyright/copyright'
import '../../components/common/search-rooms/search-rooms'