import './right-column.scss'
import '../../../components/elements/dropdowns/dropdown'
import '../../../components/elements/pagination/pagination'
import '../../../components/elements/bullet-list/bullet-list'
import '../right-column/container-buttons/container-buttons'
import '../../../components/common/slider/slider'